### ISSUE TITLE
gitignore netbeans

### ISSUE THREAD

**Issue by isjhar** [DatabaseLabTelU/GraphingNews#2]
tolong dong yang bisa nyari tau untuk project java netbeans versi ant yang perlu diignore apa aja. biar ntar gak jadi problem conflict dan file yang diupload tidak terlalu besar. yang bisa ngurus ini, tolong bilang ya

**Comment by feber** [comment]
Yang saya tau nbpoject gak wajib, karena isinya menyangkut versi jdk dan beberapa hal lain (yang saya belum tau)

**Comment by isjhar** [comment]
coba cari tahu dulu, klo dah yakin, sung direvisi gitignorenya ya. biasanya yg diignore itu yg digenerate IDE nya
